// Comprehensive Mock Data for FreshCatch Demo
import type { FishProduct, Recipe, Order } from '@/types';

export const MOCK_PRODUCTS: FishProduct[] = [
  {
    id: '1',
    name_english: 'Emperor / Eari / Sheri / Shaari',
    name_tamil: 'விலான்',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Premium Emperor fish with firm white flesh. Excellent for grilling and frying.',
    price_per_kg: 399,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/e/m/emperor_eari_whole.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 98, protein: 21, fat: 1.8, omega3: 0.8 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.7,
    reviews_count: 145,
    best_for: ['Fry', 'Grill', 'Curry'],
  },
  {
    id: '2',
    name_english: 'Black Pomfret / Karutha Avoli / Halwa Fish',
    name_tamil: 'கருப்பு வாவல்',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Premium black pomfret with delicate flavor. Perfect for steaming and frying.',
    price_per_kg: 899,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/b/l/black_pomfret_whole_2.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 96, protein: 19, fat: 2.1, omega3: 1.0 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.8,
    reviews_count: 198,
    best_for: ['Fry', 'Steam', 'Grill'],
  },
  {
    id: '3',
    name_english: 'Marine Milk Fish / Poomeen / Paal (Large)',
    name_tamil: 'பால் மீன்',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Large marine milk fish with mild flavor. Great for curries and frying.',
    price_per_kg: 449,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/m/a/marine_milk_fish_poomeen_large_whole.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 102, protein: 20, fat: 2.5, omega3: 0.7 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.5,
    reviews_count: 167,
    best_for: ['Curry', 'Fry'],
  },
  {
    id: '4',
    name_english: 'Mahi Mahi / Pulli Motha',
    name_tamil: 'புள்ளி மோதா',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Premium Mahi Mahi with firm texture. Excellent for grilling and baking.',
    price_per_kg: 419,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/m/a/mahi-mahi.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
      { id: 'steaks', name: 'Steaks', name_tamil: 'துண்டுகள்', price_modifier: 30 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 109, protein: 23, fat: 1.2, omega3: 0.6 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.9,
    reviews_count: 223,
    best_for: ['Grill', 'Bake', 'Fry'],
  },
  {
    id: '5',
    name_english: 'Premium Sardine / Mathi',
    name_tamil: 'மத்தி',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Premium quality sardines, rich in omega-3. Perfect for frying.',
    price_per_kg: 319,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/m/a/mathi_whole_510g_special.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 208, protein: 25, fat: 11, omega3: 2.2 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.6,
    reviews_count: 289,
    best_for: ['Fry', 'Curry'],
  },
  {
    id: '6',
    name_english: 'Pink Perch / Kilimeen / Sankara Meen',
    name_tamil: 'கிளிமீன்',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Fresh pink perch with delicate flavor. Great for frying and curries.',
    price_per_kg: 399,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/p/i/pink_perch_whole_1_1.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 94, protein: 19, fat: 1.9, omega3: 0.7 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.7,
    reviews_count: 178,
    best_for: ['Fry', 'Curry'],
  },
  {
    id: '7',
    name_english: 'Anchovy / Netholi (Large)',
    name_tamil: 'நெத்திலி',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Large anchovies, perfect for crispy fry. Rich in calcium and omega-3.',
    price_per_kg: 399,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/a/n/anchovies_whole_large_1_.jpeg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 20 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 131, protein: 20, fat: 4.8, omega3: 1.5 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.5,
    reviews_count: 234,
    best_for: ['Fry', 'Kulambu'],
  },
  {
    id: '8',
    name_english: 'Barracuda / Cheelavu / Thinda (Large)',
    name_tamil: 'ஓலா',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Large barracuda with firm flesh. Excellent for steaks and curries.',
    price_per_kg: 425,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/b/a/baracuda_whole_1_1.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
      { id: 'steaks', name: 'Steaks', name_tamil: 'துண்டுகள்', price_modifier: 30 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 107, protein: 21, fat: 2.3, omega3: 0.9 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.6,
    reviews_count: 156,
    best_for: ['Curry', 'Fry', 'Grill'],
  },
  {
    id: '9',
    name_english: 'Long Rayed Silver Biddy / Pranjil',
    name_tamil: 'சாளை',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Fresh silver biddy with sweet flavor. Perfect for frying.',
    price_per_kg: 349,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/s/i/silver_biddy_pranjil_whole.jpeg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 92, protein: 18, fat: 1.6, omega3: 0.6 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.4,
    reviews_count: 134,
    best_for: ['Fry', 'Curry'],
  },
  {
    id: '10',
    name_english: 'Mackerel / Ayala / Bangda (10 to 14)',
    name_tamil: 'அயிலை',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Fresh mackerel, great for everyday cooking. Affordable and nutritious.',
    price_per_kg: 269,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/m/a/mackeral_10-14c_whole.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 205, protein: 19, fat: 13.9, omega3: 2.6 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.7,
    reviews_count: 312,
    best_for: ['Fry', 'Curry', 'Kulambu'],
  },
  {
    id: '11',
    name_english: 'White Snapper / Vela Meen',
    name_tamil: 'வெள்ளை சங்கரா',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Premium white snapper with mild sweet flavor. Excellent for grilling.',
    price_per_kg: 449,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/w/h/white-snapper-whole.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 100, protein: 20, fat: 1.3, omega3: 0.3 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.8,
    reviews_count: 156,
    best_for: ['Grill', 'Bake', 'Curry'],
  },
  {
    id: '12',
    name_english: 'Trevally / Vatta / Parai (Large)',
    name_tamil: 'பாறை',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Large trevally with firm flesh. Great for steaks and curries.',
    price_per_kg: 375,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/t/r/trevalli_large_whole.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
      { id: 'steaks', name: 'Steaks', name_tamil: 'துண்டுகள்', price_modifier: 30 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 104, protein: 21, fat: 2.1, omega3: 0.8 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.6,
    reviews_count: 187,
    best_for: ['Curry', 'Fry', 'Grill'],
  },
  {
    id: '13',
    name_english: 'Seer Fish / King Fish / Surmai / Naumeen / Vanjaram (Large)',
    name_tamil: 'வஞ்சிரம்',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Large premium seer fish steaks. Perfect for special occasions.',
    price_per_kg: 1199,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/s/e/seer_fish_whole.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
      { id: 'steaks', name: 'Steaks', name_tamil: 'துண்டுகள்', price_modifier: 30 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 109, protein: 22, fat: 2.3, omega3: 1.2 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.9,
    reviews_count: 298,
    best_for: ['Fry', 'Curry', 'Grill'],
  },
  {
    id: '14',
    name_english: 'Ribbon Fish / Thalagan / Vaala',
    name_tamil: 'வாலா',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Fresh ribbon fish with delicate texture. Excellent for frying.',
    price_per_kg: 325,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/r/i/ribbon_fish_whole_6.5g.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 97, protein: 18, fat: 2.4, omega3: 0.7 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.5,
    reviews_count: 167,
    best_for: ['Fry', 'Curry'],
  },
  {
    id: '15',
    name_english: 'Grouper / Reef Cod / Hamour (Medium)',
    name_tamil: 'கல்வா',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Medium grouper with firm white flesh. Premium quality fish.',
    price_per_kg: 489,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/g/r/grouper_medium_3.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
      { id: 'steaks', name: 'Steaks', name_tamil: 'துண்டுகள்', price_modifier: 30 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 92, protein: 19, fat: 1.0, omega3: 0.5 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.8,
    reviews_count: 201,
    best_for: ['Grill', 'Bake', 'Curry'],
  },
  {
    id: '16',
    name_english: 'Garfish / Kola / Kolameen (Large)',
    name_tamil: 'கோலா',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Large garfish with unique flavor. Great for frying.',
    price_per_kg: 357,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/g/a/garfish_whole.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 95, protein: 19, fat: 1.8, omega3: 0.6 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.4,
    reviews_count: 123,
    best_for: ['Fry', 'Curry'],
  },
  {
    id: '17',
    name_english: 'Sail Fish / Ola Meen',
    name_tamil: 'ஓலா மீன்',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Premium sail fish with firm texture. Excellent for grilling.',
    price_per_kg: 375,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/s/a/sail-fish.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
      { id: 'steaks', name: 'Steaks', name_tamil: 'துண்டுகள்', price_modifier: 30 },
    ],
    availability_status: 'limited' as const,
    nutritional_info: { calories: 112, protein: 24, fat: 1.5, omega3: 0.8 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.7,
    reviews_count: 145,
    best_for: ['Grill', 'Bake', 'Curry'],
  },
  {
    id: '18',
    name_english: 'Tuna / Choora / Choorai',
    name_tamil: 'சூரை',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Fresh tuna with rich flavor. Perfect for steaks and sushi.',
    price_per_kg: 349,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/t/u/tuna_whole_3.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
      { id: 'steaks', name: 'Steaks', name_tamil: 'துண்டுகள்', price_modifier: 30 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 144, protein: 23, fat: 4.9, omega3: 1.3 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.8,
    reviews_count: 267,
    best_for: ['Grill', 'Sushi', 'Curry'],
  },
  {
    id: '19',
    name_english: 'Anchovy / Netholi (Large) - Whole Cleaned',
    name_tamil: 'நெத்திலி - சுத்தம்',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Large whole cleaned anchovies, ready to cook. Rich in calcium and omega-3.',
    price_per_kg: 690,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/a/n/anchovy_whole_cleaned.jpg'],
    cleaning_options: [
      { id: 'cleaned', name: 'Whole Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 131, protein: 20, fat: 4.8, omega3: 1.5 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.6,
    reviews_count: 189,
    best_for: ['Fry', 'Kulambu'],
  },
  {
    id: '20',
    name_english: 'Large Marine Catfish / Etta Koon / Keluthi',
    name_tamil: 'கெளுத்தி',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Large marine catfish with firm flesh. Excellent for curries and frying.',
    price_per_kg: 375,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/c/a/catfish_whole.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
      { id: 'steaks', name: 'Steaks', name_tamil: 'துண்டுகள்', price_modifier: 30 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 105, protein: 18, fat: 2.8, omega3: 0.6 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.5,
    reviews_count: 167,
    best_for: ['Curry', 'Fry'],
  },
  {
    id: '21',
    name_english: 'Tiger Prawns (Large)',
    name_tamil: 'புலி இறால் (பெரிய)',
    category_id: 'prawns',
    category: { id: 'prawns', name_english: 'Prawns & Shrimp', name_tamil: 'இறால்' },
    description: 'Large tiger prawns, perfect for all preparations. Premium quality.',
    price_per_kg: 549,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/t/i/tiger_prawn_30_1.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'With Shell', name_tamil: 'ஓடுடன்', price_modifier: 0 },
      { id: 'cleaned', name: 'Deveined', name_tamil: 'சுத்தம்', price_modifier: 50 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 85, protein: 18, fat: 0.9, omega3: 0.5 },
    freshness_date: new Date(),
    fish_type: 'prawns' as const,
    is_active: true,
    rating: 4.8,
    reviews_count: 267,
    best_for: ['Biriyani', 'Curry', 'Fry'],
  },
  {
    id: '22',
    name_english: 'Sand Lobster / Flathead Lobster / Slipper Lobster',
    name_tamil: 'மணல் இறால்',
    category_id: 'special',
    category: { id: 'special', name_english: 'Special/Seasonal', name_tamil: 'சிறப்பு' },
    description: 'Premium sand lobster with sweet meat. Excellent for grilling.',
    price_per_kg: 399,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/s/a/san_lobster.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
    ],
    availability_status: 'limited' as const,
    nutritional_info: { calories: 90, protein: 19, fat: 1.0, omega3: 0.4 },
    freshness_date: new Date(),
    fish_type: 'special' as const,
    is_active: true,
    rating: 4.7,
    reviews_count: 123,
    best_for: ['Grill', 'Butter Garlic'],
  },
  {
    id: '23',
    name_english: 'Tiger Prawn (Super Large)',
    name_tamil: 'புலி இறால் (மிகப் பெரிய)',
    category_id: 'prawns',
    category: { id: 'prawns', name_english: 'Prawns & Shrimp', name_tamil: 'இறால்' },
    description: 'Super large tiger prawns. Get 30% cashback with code. Perfect for special occasions.',
    price_per_kg: 749,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/t/i/tiger_prawn_super_large_whole_560g.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'With Shell', name_tamil: 'ஓடுடன்', price_modifier: 0 },
      { id: 'cleaned', name: 'Deveined', name_tamil: 'சுத்தம்', price_modifier: 50 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 88, protein: 19, fat: 1.0, omega3: 0.6 },
    freshness_date: new Date(),
    fish_type: 'prawns' as const,
    is_active: true,
    rating: 4.9,
    reviews_count: 234,
    best_for: ['Biriyani', 'Grill', 'Butter Garlic'],
  },
  {
    id: '24',
    name_english: 'White and Orange Prawns / Poovalan Chemmeen',
    name_tamil: 'வெள்ளை ஆரஞ்சு இறால்',
    category_id: 'prawns',
    category: { id: 'prawns', name_english: 'Prawns & Shrimp', name_tamil: 'இறால்' },
    description: 'Mixed white and orange prawns with sweet flavor. Great for curries.',
    price_per_kg: 299,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/p/o/poovalan_chemmeen.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'With Shell', name_tamil: 'ஓடுடன்', price_modifier: 0 },
      { id: 'cleaned', name: 'Deveined', name_tamil: 'சுத்தம்', price_modifier: 40 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 80, protein: 17, fat: 0.8, omega3: 0.4 },
    freshness_date: new Date(),
    fish_type: 'prawns' as const,
    is_active: true,
    rating: 4.6,
    reviews_count: 189,
    best_for: ['Curry', 'Fry'],
  },
  {
    id: '25',
    name_english: 'Tiger Prawn (Super Jumbo)',
    name_tamil: 'புலி இறால் (சூப்பர் ஜம்போ)',
    category_id: 'prawns',
    category: { id: 'prawns', name_english: 'Prawns & Shrimp', name_tamil: 'இறால்' },
    description: 'Super jumbo tiger prawns. Premium quality for special occasions.',
    price_per_kg: 799,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/t/i/tiger_prawn_super_jumbo_whole.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'With Shell', name_tamil: 'ஓடுடன்', price_modifier: 0 },
      { id: 'cleaned', name: 'Deveined', name_tamil: 'சுத்தம்', price_modifier: 50 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 90, protein: 19, fat: 1.0, omega3: 0.6 },
    freshness_date: new Date(),
    fish_type: 'prawns' as const,
    is_active: true,
    rating: 4.9,
    reviews_count: 198,
    best_for: ['Grill', 'Biriyani', 'Butter Garlic'],
  },
  {
    id: '26',
    name_english: 'Small Cleaned Prawns / Kucho Chingdi - Peeled, Cleaned but not Deveined',
    name_tamil: 'சிறிய சுத்தம் இறால்',
    category_id: 'prawns',
    category: { id: 'prawns', name_english: 'Prawns & Shrimp', name_tamil: 'இறால்' },
    description: 'Small cleaned prawns, peeled and ready to cook. Perfect for quick meals.',
    price_per_kg: 499,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/s/m/small_cleaned_prawns.jpg'],
    cleaning_options: [
      { id: 'peeled', name: 'Peeled & Cleaned', name_tamil: 'தோல் நீக்கியது', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 78, protein: 16, fat: 0.7, omega3: 0.4 },
    freshness_date: new Date(),
    fish_type: 'prawns' as const,
    is_active: true,
    rating: 4.7,
    reviews_count: 212,
    best_for: ['Fry', 'Curry', 'Biriyani'],
  },
  {
    id: '27',
    name_english: 'Squid / Koonthal - Rings (240g to 200g Pack)',
    name_tamil: 'கணவாய் வளையங்கள்',
    category_id: 'squid',
    category: { id: 'squid', name_english: 'Squid & Cuttlefish', name_tamil: 'கணவாய்' },
    description: 'Pre-cut squid rings, ready to fry. Convenient pack size.',
    price_per_kg: 425,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/s/q/squid_rings_1_1_2.jpg'],
    cleaning_options: [
      { id: 'rings', name: 'Rings', name_tamil: 'வளையங்கள்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 92, protein: 15, fat: 1.4, omega3: 0.5 },
    freshness_date: new Date(),
    fish_type: 'squid' as const,
    is_active: true,
    rating: 4.8,
    reviews_count: 167,
    best_for: ['Fry', 'Roast'],
  },
  {
    id: '28',
    name_english: 'Indian Prawns (60+ Count/kg)',
    name_tamil: 'இந்திய இறால் (60+)',
    category_id: 'prawns',
    category: { id: 'prawns', name_english: 'Prawns & Shrimp', name_tamil: 'இறால்' },
    description: 'Medium-sized Indian prawns, 60+ count per kg. Great value for money.',
    price_per_kg: 457,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/i/n/indian_prawns_whole11169_4__2_3.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'With Shell', name_tamil: 'ஓடுடன்', price_modifier: 0 },
      { id: 'cleaned', name: 'Deveined', name_tamil: 'சுத்தம்', price_modifier: 40 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 83, protein: 17, fat: 0.9, omega3: 0.5 },
    freshness_date: new Date(),
    fish_type: 'prawns' as const,
    is_active: true,
    rating: 4.7,
    reviews_count: 234,
    best_for: ['Curry', 'Fry', 'Biriyani'],
  },
  {
    id: '29',
    name_english: 'Indian Prawns (50+ Count/kg)',
    name_tamil: 'இந்திய இறால் (50+)',
    category_id: 'prawns',
    category: { id: 'prawns', name_english: 'Prawns & Shrimp', name_tamil: 'இறால்' },
    description: 'Larger Indian prawns, 50+ count per kg. Perfect for all preparations.',
    price_per_kg: 449,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/i/n/indian_prawns_whole11169_4__2_3.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'With Shell', name_tamil: 'ஓடுடன்', price_modifier: 0 },
      { id: 'cleaned', name: 'Deveined', name_tamil: 'சுத்தம்', price_modifier: 40 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 85, protein: 18, fat: 0.9, omega3: 0.5 },
    freshness_date: new Date(),
    fish_type: 'prawns' as const,
    is_active: true,
    rating: 4.7,
    reviews_count: 198,
    best_for: ['Curry', 'Fry', 'Biriyani'],
  },
  {
    id: '30',
    name_english: 'Wild Caught Prawn / Kazhanthan (80 to 90 Count)',
    name_tamil: 'காட்டு இறால்',
    category_id: 'prawns',
    category: { id: 'prawns', name_english: 'Prawns & Shrimp', name_tamil: 'இறால்' },
    description: 'Wild caught prawns with natural flavor. 80-90 count per kg.',
    price_per_kg: 389,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/k/a/kazhanthan_small.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'With Shell', name_tamil: 'ஓடுடன்', price_modifier: 0 },
      { id: 'cleaned', name: 'Deveined', name_tamil: 'சுத்தம்', price_modifier: 35 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 80, protein: 16, fat: 0.8, omega3: 0.4 },
    freshness_date: new Date(),
    fish_type: 'prawns' as const,
    is_active: true,
    rating: 4.6,
    reviews_count: 156,
    best_for: ['Curry', 'Fry'],
  },
  {
    id: '31',
    name_english: 'Rohu / Rahu / கெண்டை / Kendai (1kg to 2kg)',
    name_tamil: 'கெண்டை',
    category_id: 'freshwater',
    category: { id: 'freshwater', name_english: 'Freshwater Fish', name_tamil: 'நன்னீர் மீன்' },
    description: 'Fresh Rohu fish, perfect for traditional fish curry. 1-2kg size.',
    price_per_kg: 299,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/r/o/rohu_12.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 97, protein: 17, fat: 2.2, omega3: 0.6 },
    freshness_date: new Date(),
    fish_type: 'freshwater' as const,
    is_active: true,
    rating: 4.7,
    reviews_count: 234,
    best_for: ['Curry', 'Fry'],
  },
  {
    id: '32',
    name_english: 'Snake Head Fish / Varaal / வரால்',
    name_tamil: 'வரால்',
    category_id: 'freshwater',
    category: { id: 'freshwater', name_english: 'Freshwater Fish', name_tamil: 'நன்னீர் மீன்' },
    description: 'Premium snake head fish with firm flesh. Excellent for curries.',
    price_per_kg: 399,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/s/n/snakehead_whole_.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 105, protein: 19, fat: 2.5, omega3: 0.7 },
    freshness_date: new Date(),
    fish_type: 'freshwater' as const,
    is_active: true,
    rating: 4.8,
    reviews_count: 189,
    best_for: ['Curry', 'Soup'],
  },
  {
    id: '33',
    name_english: 'Fresh Indian Baasa / Pangasius / Pangas',
    name_tamil: 'பங்காசியஸ்',
    category_id: 'freshwater',
    category: { id: 'freshwater', name_english: 'Freshwater Fish', name_tamil: 'நன்னீர் மீன்' },
    description: 'Fresh Indian Baasa fish with mild flavor. Great for frying.',
    price_per_kg: 149,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/b/a/baasa_whole.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
      { id: 'fillets', name: 'Fillets', name_tamil: 'துண்டுகள்', price_modifier: 30 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 90, protein: 15, fat: 2.0, omega3: 0.4 },
    freshness_date: new Date(),
    fish_type: 'freshwater' as const,
    is_active: true,
    rating: 4.5,
    reviews_count: 312,
    best_for: ['Fry', 'Curry'],
  },
  {
    id: '34',
    name_english: 'Striped Mullet / Kanambu / Pashe / Boi / Flathead Grey Mullet',
    name_tamil: 'கணாம்பு',
    category_id: 'freshwater',
    category: { id: 'freshwater', name_english: 'Freshwater Fish', name_tamil: 'நன்னீர் மீன்' },
    description: 'Striped mullet with delicate flavor. Perfect for frying.',
    price_per_kg: 325,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/k/a/kanambu.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 98, protein: 18, fat: 2.1, omega3: 0.5 },
    freshness_date: new Date(),
    fish_type: 'freshwater' as const,
    is_active: true,
    rating: 4.6,
    reviews_count: 167,
    best_for: ['Fry', 'Curry'],
  },
  {
    id: '35',
    name_english: 'Tangra / Tyangra / Koori',
    name_tamil: 'தங்க்ரா',
    category_id: 'freshwater',
    category: { id: 'freshwater', name_english: 'Freshwater Fish', name_tamil: 'நன்னீர் மீன்' },
    description: 'Small Tangra fish, perfect for crispy fry. Popular in Bengali cuisine.',
    price_per_kg: 599,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/t/e/tengra.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 20 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 95, protein: 17, fat: 2.3, omega3: 0.6 },
    freshness_date: new Date(),
    fish_type: 'freshwater' as const,
    is_active: true,
    rating: 4.7,
    reviews_count: 145,
    best_for: ['Fry', 'Curry'],
  },
  {
    id: '36',
    name_english: 'Bhetki / Barramundi / Asian Seabass / Kalangi',
    name_tamil: 'பெத்கி',
    category_id: 'freshwater',
    category: { id: 'freshwater', name_english: 'Freshwater Fish', name_tamil: 'நன்னீர் மீன்' },
    description: 'Premium Bhetki fish with firm white flesh. Get 30% cashback.',
    price_per_kg: 547,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/b/h/bhetki_1.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
      { id: 'fillets', name: 'Fillets', name_tamil: 'துண்டுகள்', price_modifier: 40 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 102, protein: 20, fat: 2.0, omega3: 0.7 },
    freshness_date: new Date(),
    fish_type: 'freshwater' as const,
    is_active: true,
    rating: 4.9,
    reviews_count: 298,
    best_for: ['Fry', 'Curry', 'Grill'],
  },
  {
    id: '37',
    name_english: 'River Pomfret / Roopchand / ரூப்சந்த்',
    name_tamil: 'ரூப்சந்த்',
    category_id: 'freshwater',
    category: { id: 'freshwater', name_english: 'Freshwater Fish', name_tamil: 'நன்னீர் மீன்' },
    description: 'River pomfret with delicate flavor. Perfect for steaming.',
    price_per_kg: 219,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/r/u/rupchanda_whole_1_1_.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 93, protein: 18, fat: 1.8, omega3: 0.5 },
    freshness_date: new Date(),
    fish_type: 'freshwater' as const,
    is_active: true,
    rating: 4.6,
    reviews_count: 178,
    best_for: ['Steam', 'Fry', 'Curry'],
  },
  {
    id: '38',
    name_english: 'Freshwater Sole Fish / Elachil',
    name_tamil: 'எலச்சில்',
    category_id: 'freshwater',
    category: { id: 'freshwater', name_english: 'Freshwater Fish', name_tamil: 'நன்னீர் மீன்' },
    description: 'Freshwater sole fish with mild flavor. Great for frying.',
    price_per_kg: 249,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/f/r/freshwater_sole_fish.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 88, protein: 16, fat: 1.5, omega3: 0.4 },
    freshness_date: new Date(),
    fish_type: 'freshwater' as const,
    is_active: true,
    rating: 4.5,
    reviews_count: 134,
    best_for: ['Fry', 'Curry'],
  },
  {
    id: '39',
    name_english: 'Paral / Giant Danio',
    name_tamil: 'பரல்',
    category_id: 'freshwater',
    category: { id: 'freshwater', name_english: 'Freshwater Fish', name_tamil: 'நன்னீர் மீன்' },
    description: 'Small Paral fish, perfect for crispy fry. Popular choice.',
    price_per_kg: 249,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/g/i/giant_danio_whole_2_2.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 15 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 90, protein: 16, fat: 1.9, omega3: 0.5 },
    freshness_date: new Date(),
    fish_type: 'freshwater' as const,
    is_active: true,
    rating: 4.6,
    reviews_count: 156,
    best_for: ['Fry', 'Curry'],
  },
  {
    id: '40',
    name_english: 'River Sole / Vaka Varal',
    name_tamil: 'வாகா வரால்',
    category_id: 'freshwater',
    category: { id: 'freshwater', name_english: 'Freshwater Fish', name_tamil: 'நன்னீர் மீன்' },
    description: 'River sole with firm flesh. Excellent for frying and curries.',
    price_per_kg: 349,
    images: ['https://static.freshtohome.com/cdn-cgi/image/width=600/https://static.freshtohome.com/media/catalog/product/v/a/vaaka_varal.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 96, protein: 18, fat: 2.0, omega3: 0.6 },
    freshness_date: new Date(),
    fish_type: 'freshwater' as const,
    is_active: true,
    rating: 4.7,
    reviews_count: 167,
    best_for: ['Fry', 'Curry'],
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD001',
    user_id: 'user1',
    items: [
      { product: MOCK_PRODUCTS[0], quantity: 1, unit: 'kg', cleaning_type: 'steaks', total_price: 880 },
      { product: MOCK_PRODUCTS[2], quantity: 0.5, unit: 'kg', cleaning_type: 'cleaned', total_price: 375 },
    ],
    subtotal: 1255,
    delivery_charge: 0,
    discount_amount: 50,
    total_amount: 1205,
    order_status: 'delivered' as const,
    payment_method: 'upi' as const,
    payment_status: 'paid' as const,
    delivery_slot: { name: 'Morning Delivery', time: '8:00 AM - 12:00 PM' },
    delivery_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    address: {
      full_address: '42, Gandhi Street, T. Nagar',
      landmark: 'Near Pondy Bazaar',
      city: 'Chennai',
      pincode: '600017',
    },
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'ORD002',
    user_id: 'user1',
    items: [
      { product: MOCK_PRODUCTS[1], quantity: 2, unit: 'piece', cleaning_type: 'cleaned', total_price: 760 },
    ],
    subtotal: 760,
    delivery_charge: 30,
    discount_amount: 0,
    total_amount: 790,
    order_status: 'out_for_delivery' as const,
    payment_method: 'cod' as const,
    payment_status: 'pending' as const,
    delivery_slot: { name: 'Evening Delivery', time: '4:00 PM - 7:00 PM' },
    delivery_date: new Date(),
    address: {
      full_address: '42, Gandhi Street, T. Nagar',
      landmark: 'Near Pondy Bazaar',
      city: 'Chennai',
      pincode: '600017',
    },
    delivery_partner: {
      name: 'Rajan K',
      phone: '+91 98765 43210',
      photo: '/images/delivery/rajan.jpg',
    },
    tracking: {
      current_lat: 13.0418,
      current_lng: 80.2341,
      eta: '25 mins',
    },
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    id: 'ORD003',
    user_id: 'user1',
    items: [
      { product: MOCK_PRODUCTS[4], quantity: 1, unit: 'kg', cleaning_type: 'cleaned', total_price: 510 },
      { product: MOCK_PRODUCTS[7], quantity: 0.5, unit: 'kg', cleaning_type: 'cleaned', total_price: 110 },
    ],
    subtotal: 620,
    delivery_charge: 0,
    discount_amount: 0,
    total_amount: 620,
    order_status: 'processing' as const,
    payment_method: 'upi' as const,
    payment_status: 'paid' as const,
    delivery_slot: { name: 'Sunrise Delivery', time: '6:00 AM - 8:00 AM' },
    delivery_date: new Date(Date.now() + 24 * 60 * 60 * 1000),
    address: {
      full_address: '15, Lake View Road, Nungambakkam',
      landmark: 'Opposite to Park',
      city: 'Chennai',
      pincode: '600034',
    },
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
];

export const MOCK_RECIPES: Recipe[] = [
  {
    id: '1',
    title_english: 'Meen Kulambu (Fish Curry)',
    title_tamil: 'மீன் குழம்பு',
    fish_product: MOCK_PRODUCTS[0],
    video_url: 'https://www.youtube.com/embed/-kPEvUSZkEM',
    thumbnail: 'https://img.youtube.com/vi/-kPEvUSZkEM/maxresdefault.jpg',
    content: 'Traditional Tamil Nadu style fish curry with tamarind and spices.',
    difficulty_level: 'medium' as const,
    cooking_time: 45,
    servings: 4,
    cuisine_type: 'Tamil',
    ingredients: [
      { name: 'Seer Fish', quantity: '500g', is_fish: true },
      { name: 'Tamarind', quantity: '1 lemon size', is_fish: false },
      { name: 'Onion', quantity: '2 medium', is_fish: false },
      { name: 'Tomato', quantity: '2 medium', is_fish: false },
      { name: 'Sambar powder', quantity: '2 tbsp', is_fish: false },
      { name: 'Turmeric', quantity: '1/2 tsp', is_fish: false },
    ],
    steps: [
      { step_number: 1, instruction: 'Clean and marinate fish with turmeric and salt' },
      { step_number: 2, instruction: 'Soak tamarind in warm water and extract juice' },
      { step_number: 3, instruction: 'Heat oil and splutter mustard seeds, fenugreek' },
      { step_number: 4, instruction: 'Add onions and sauté until golden' },
      { step_number: 5, instruction: 'Add tomatoes and cook until soft' },
      { step_number: 6, instruction: 'Add sambar powder, tamarind juice and simmer' },
      { step_number: 7, instruction: 'Gently add fish pieces and cook for 10-12 mins' },
    ],
    rating: 4.8,
    reviews_count: 156,
    is_active: true,
  },
  {
    id: '2',
    title_english: 'Prawn Biriyani',
    title_tamil: 'இறால் பிரியாணி',
    fish_product: MOCK_PRODUCTS[2],
    video_url: 'https://www.youtube.com/embed/OYo9kHRxeH0',
    thumbnail: 'https://img.youtube.com/vi/OYo9kHRxeH0/maxresdefault.jpg',
    content: 'Aromatic prawn biriyani with basmati rice and special spices.',
    difficulty_level: 'hard' as const,
    cooking_time: 60,
    servings: 6,
    cuisine_type: 'Tamil',
    ingredients: [
      { name: 'Tiger Prawns', quantity: '500g', is_fish: true },
      { name: 'Basmati Rice', quantity: '2 cups', is_fish: false },
      { name: 'Onion', quantity: '3 large', is_fish: false },
      { name: 'Yogurt', quantity: '1/2 cup', is_fish: false },
      { name: 'Biriyani masala', quantity: '2 tbsp', is_fish: false },
    ],
    steps: [
      { step_number: 1, instruction: 'Clean prawns and marinate with yogurt and spices' },
      { step_number: 2, instruction: 'Soak basmati rice for 30 minutes' },
      { step_number: 3, instruction: 'Fry onions until golden brown for garnish' },
      { step_number: 4, instruction: 'Cook prawns with spices until done' },
      { step_number: 5, instruction: 'Layer rice and prawn masala, dum cook for 20 mins' },
    ],
    rating: 4.9,
    reviews_count: 203,
    is_active: true,
  },
  {
    id: '3',
    title_english: 'Fish Fry (Meen Varuval)',
    title_tamil: 'மீன் வறுவல்',
    fish_product: MOCK_PRODUCTS[1],
    video_url: 'https://www.youtube.com/embed/o8lDCY2_jyw',
    thumbnail: 'https://img.youtube.com/vi/o8lDCY2_jyw/maxresdefault.jpg',
    content: 'Crispy South Indian style fish fry with aromatic spices.',
    difficulty_level: 'easy' as const,
    cooking_time: 25,
    servings: 4,
    cuisine_type: 'Tamil',
    ingredients: [
      { name: 'Pomfret', quantity: '4 pieces', is_fish: true },
      { name: 'Red chilli powder', quantity: '2 tbsp', is_fish: false },
      { name: 'Turmeric', quantity: '1/2 tsp', is_fish: false },
      { name: 'Ginger garlic paste', quantity: '1 tbsp', is_fish: false },
      { name: 'Lemon juice', quantity: '2 tbsp', is_fish: false },
    ],
    steps: [
      { step_number: 1, instruction: 'Make slits on both sides of the fish' },
      { step_number: 2, instruction: 'Mix all spices with lemon juice to make paste' },
      { step_number: 3, instruction: 'Apply paste on fish and marinate for 30 mins' },
      { step_number: 4, instruction: 'Heat oil in a pan and shallow fry until crispy' },
    ],
    rating: 4.7,
    reviews_count: 312,
    is_active: true,
  },
  {
    id: '4',
    title_english: 'Crab Masala',
    title_tamil: 'நண்டு மசாலா',
    fish_product: MOCK_PRODUCTS[4],
    video_url: 'https://www.youtube.com/embed/2BSVhda6tWs',
    thumbnail: 'https://img.youtube.com/vi/2BSVhda6tWs/maxresdefault.jpg',
    content: 'Spicy Chettinad style crab masala with coconut.',
    difficulty_level: 'medium' as const,
    cooking_time: 50,
    servings: 4,
    cuisine_type: 'Chettinad',
    ingredients: [
      { name: 'Crab', quantity: '1 kg', is_fish: true },
      { name: 'Coconut', quantity: '1/2 cup grated', is_fish: false },
      { name: 'Onion', quantity: '2 medium', is_fish: false },
      { name: 'Curry leaves', quantity: '2 sprigs', is_fish: false },
    ],
    steps: [
      { step_number: 1, instruction: 'Clean crabs and separate claws' },
      { step_number: 2, instruction: 'Grind coconut with spices for masala' },
      { step_number: 3, instruction: 'Cook crabs with masala until done' },
    ],
    rating: 4.6,
    reviews_count: 89,
    is_active: true,
  },
  {
    id: '5',
    title_english: 'Kerala Fish Molee',
    title_tamil: 'கேரளா மீன் மொய்லி',
    fish_product: MOCK_PRODUCTS[8],
    video_url: 'https://www.youtube.com/embed/9qXZ_aous-Y',
    thumbnail: 'https://img.youtube.com/vi/9qXZ_aous-Y/maxresdefault.jpg',
    content: 'Creamy Kerala style fish curry with coconut milk.',
    difficulty_level: 'easy' as const,
    cooking_time: 35,
    servings: 4,
    cuisine_type: 'Kerala',
    ingredients: [
      { name: 'Red Snapper', quantity: '500g', is_fish: true },
      { name: 'Coconut milk', quantity: '2 cups', is_fish: false },
      { name: 'Green chillies', quantity: '3-4', is_fish: false },
      { name: 'Ginger', quantity: '1 inch', is_fish: false },
    ],
    steps: [
      { step_number: 1, instruction: 'Marinate fish with turmeric and salt' },
      { step_number: 2, instruction: 'Sauté onions, ginger, green chillies' },
      { step_number: 3, instruction: 'Add coconut milk and bring to simmer' },
      { step_number: 4, instruction: 'Add fish and cook gently for 10 mins' },
    ],
    rating: 4.8,
    reviews_count: 134,
    is_active: true,
  },
  {
    id: '6',
    title_english: 'Squid Roast',
    title_tamil: 'கணவாய் வறுவல்',
    fish_product: MOCK_PRODUCTS[6],
    video_url: 'https://www.youtube.com/embed/7y0kgjyhHZ8',
    thumbnail: 'https://img.youtube.com/vi/7y0kgjyhHZ8/maxresdefault.jpg',
    content: 'Spicy dry squid roast with pepper and curry leaves.',
    difficulty_level: 'easy' as const,
    cooking_time: 20,
    servings: 3,
    cuisine_type: 'Tamil',
    ingredients: [
      { name: 'Squid rings', quantity: '400g', is_fish: true },
      { name: 'Black pepper', quantity: '1 tbsp', is_fish: false },
      { name: 'Curry leaves', quantity: '2 sprigs', is_fish: false },
    ],
    steps: [
      { step_number: 1, instruction: 'Clean squid and cut into rings' },
      { step_number: 2, instruction: 'Marinate with spices' },
      { step_number: 3, instruction: 'Stir fry on high heat until done' },
    ],
    rating: 4.5,
    reviews_count: 78,
    is_active: true,
  },
];

export const MOCK_USER = {
  id: 'user1',
  name: 'Priya Sharma',
  mobile_primary: '+91 98765 43210',
  mobile_alternative: '+91 98765 43211',
  email: 'priya.sharma@email.com',
  referral_code: 'PRIYA50',
  referred_by: null,
  preferred_language: 'en' as const,
  profile_picture: '/images/users/priya.jpg',
  wallet_balance: 150,
  total_orders: 23,
  addresses: [
    {
      id: 'addr1',
      full_address: '42, Gandhi Street, T. Nagar',
      landmark: 'Near Pondy Bazaar',
      city: 'Chennai',
      pincode: '600017',
      latitude: 13.0418,
      longitude: 80.2341,
      is_default: true,
      address_type: 'home' as const,
    },
    {
      id: 'addr2',
      full_address: '15, Lake View Road, Nungambakkam',
      landmark: 'Opposite to Park',
      city: 'Chennai',
      pincode: '600034',
      latitude: 13.0569,
      longitude: 80.2425,
      is_default: false,
      address_type: 'work' as const,
    },
  ],
  referrals: [
    { name: 'Anitha R', date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000), earned: 50, status: 'credited' },
    { name: 'Kumar S', date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), earned: 50, status: 'credited' },
    { name: 'Lakshmi M', date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), earned: 50, status: 'pending' },
  ],
};

export const MOCK_CART = {
  items: [
    {
      id: 'cart1',
      product: MOCK_PRODUCTS[0],
      quantity: 1,
      unit: 'kg' as const,
      cleaning_type: 'steaks',
      unit_price: 880,
      total_price: 880,
    },
    {
      id: 'cart2',
      product: MOCK_PRODUCTS[2],
      quantity: 0.5,
      unit: 'kg' as const,
      cleaning_type: 'cleaned',
      unit_price: 700,
      total_price: 350,
    },
  ],
  subtotal: 1230,
  delivery_charge: 0,
  discount_amount: 50,
  coupon_code: 'FIRST50',
  total: 1180,
};

// Admin Dashboard Stats
export const ADMIN_STATS = {
  today: {
    orders: 47,
    revenue: 42350,
    new_customers: 12,
    avg_order_value: 901,
  },
  week: {
    orders: 312,
    revenue: 287650,
    new_customers: 67,
    avg_order_value: 922,
  },
  month: {
    orders: 1247,
    revenue: 1156780,
    new_customers: 234,
    avg_order_value: 928,
  },
  recent_orders: MOCK_ORDERS,
  low_stock: [
    { product: MOCK_PRODUCTS[3], stock: 5 },
    { product: MOCK_PRODUCTS[10], stock: 3 },
  ],
  top_products: [
    { product: MOCK_PRODUCTS[0], sold: 156 },
    { product: MOCK_PRODUCTS[2], sold: 134 },
    { product: MOCK_PRODUCTS[1], sold: 98 },
  ],
};
