// Comprehensive Mock Data for FreshCatch Demo

export const MOCK_PRODUCTS = [
  {
    id: '1',
    name_english: 'Seer Fish (Vanjaram)',
    name_tamil: 'வஞ்சிரம்',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Premium quality Seer fish, known for its firm texture and rich taste. Perfect for frying, grilling or making traditional fish curry.',
    description_tamil: 'உயர்தர வஞ்சிரம் மீன், அதன் உறுதியான அமைப்பு மற்றும் சுவைக்கு பெயர் பெற்றது.',
    price_per_kg: 850,
    price_per_piece: 450,
    images: ['/images/fish/sea-fish/seer-1.jpg', '/images/fish/sea-fish/seer-2.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
      { id: 'steaks', name: 'Steaks', name_tamil: 'துண்டுகள்', price_modifier: 30 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 109, protein: 22, fat: 2.3, omega3: 1.2 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.8,
    reviews_count: 256,
    best_for: ['Fry', 'Curry', 'Grill'],
  },
  {
    id: '2',
    name_english: 'Pomfret (White)',
    name_tamil: 'வெள்ளை வாவல்',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Fresh white pomfret with delicate flavor. Excellent for shallow frying or steaming. A family favorite.',
    price_per_kg: 750,
    price_per_piece: 380,
    images: ['/images/fish/sea-fish/pomfret-1.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 95, protein: 20, fat: 1.5, omega3: 0.9 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.7,
    reviews_count: 189,
    best_for: ['Fry', 'Steam', 'Tawa'],
  },
  {
    id: '3',
    name_english: 'Tiger Prawns',
    name_tamil: 'புலி இறால்',
    category_id: 'prawns',
    category: { id: 'prawns', name_english: 'Prawns & Shrimp', name_tamil: 'இறால்' },
    description: 'Large, succulent tiger prawns. Perfect for biriyani, curry, or grilled preparations.',
    price_per_kg: 650,
    images: ['/images/fish/prawns/prawns-1.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'With Shell', name_tamil: 'ஓடுடன்', price_modifier: 0 },
      { id: 'cleaned', name: 'Deveined', name_tamil: 'சுத்தம்', price_modifier: 50 },
      { id: 'peeled', name: 'Peeled', name_tamil: 'தோல் நீக்கியது', price_modifier: 80 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 85, protein: 18, fat: 0.9, omega3: 0.5 },
    freshness_date: new Date(),
    fish_type: 'prawns' as const,
    is_active: true,
    rating: 4.9,
    reviews_count: 312,
    best_for: ['Biriyani', 'Curry', 'Grill', 'Fry'],
  },
  {
    id: '4',
    name_english: 'King Fish (Neymeen)',
    name_tamil: 'நெய்மீன்',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Rich and flavorful King fish steaks. Great for curry or shallow fry. A premium choice.',
    price_per_kg: 720,
    price_per_piece: 350,
    images: ['/images/fish/sea-fish/kingfish-1.jpg'],
    cleaning_options: [
      { id: 'steaks', name: 'Steaks', name_tamil: 'துண்டுகள்', price_modifier: 0 },
      { id: 'fillet', name: 'Fillet', name_tamil: 'ஃபில்லட்', price_modifier: 50 },
    ],
    availability_status: 'limited' as const,
    nutritional_info: { calories: 105, protein: 21, fat: 2.0, omega3: 1.0 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.6,
    reviews_count: 145,
    best_for: ['Curry', 'Fry', 'Grill'],
  },
  {
    id: '5',
    name_english: 'Crab (Blue Swimming)',
    name_tamil: 'நண்டு',
    category_id: 'crabs',
    category: { id: 'crabs', name_english: 'Crabs', name_tamil: 'நண்டு' },
    description: 'Fresh blue swimming crabs, perfect for nandu kulambu or pepper crab.',
    price_per_kg: 480,
    images: ['/images/fish/crabs/crab-1.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole Live', name_tamil: 'உயிருடன்', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 30 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 87, protein: 18, fat: 1.1, omega3: 0.4 },
    freshness_date: new Date(),
    fish_type: 'crabs' as const,
    is_active: true,
    rating: 4.5,
    reviews_count: 98,
    best_for: ['Curry', 'Pepper Fry', 'Masala'],
  },
  {
    id: '6',
    name_english: 'Rohu (Katla)',
    name_tamil: 'கெண்டை',
    category_id: 'river',
    category: { id: 'river', name_english: 'River Fish', name_tamil: 'ஆற்று மீன்' },
    description: 'Fresh water Rohu fish, ideal for Bengali style preparations and fish curry.',
    price_per_kg: 280,
    images: ['/images/fish/river-fish/rohu-1.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
      { id: 'pieces', name: 'Cut Pieces', name_tamil: 'துண்டுகள்', price_modifier: 20 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 97, protein: 17, fat: 2.4, omega3: 0.6 },
    freshness_date: new Date(),
    fish_type: 'river' as const,
    is_active: true,
    rating: 4.4,
    reviews_count: 167,
    best_for: ['Curry', 'Fry'],
  },
  {
    id: '7',
    name_english: 'Squid (Kanava)',
    name_tamil: 'கணவாய்',
    category_id: 'squid',
    category: { id: 'squid', name_english: 'Squid & Cuttlefish', name_tamil: 'கணவாய்' },
    description: 'Fresh squid rings, perfect for frying or making spicy squid roast.',
    price_per_kg: 380,
    images: ['/images/fish/squid/squid-1.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'rings', name: 'Rings', name_tamil: 'வளையங்கள்', price_modifier: 40 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 30 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 92, protein: 15, fat: 1.4, omega3: 0.5 },
    freshness_date: new Date(),
    fish_type: 'squid' as const,
    is_active: true,
    rating: 4.3,
    reviews_count: 89,
    best_for: ['Fry', 'Roast', 'Curry'],
  },
  {
    id: '8',
    name_english: 'Mackerel (Ayala)',
    name_tamil: 'அயிலை',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Fresh mackerel, great for everyday cooking. Affordable and nutritious.',
    price_per_kg: 220,
    images: ['/images/fish/sea-fish/mackerel-1.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 205, protein: 19, fat: 13.9, omega3: 2.6 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.5,
    reviews_count: 234,
    best_for: ['Fry', 'Curry', 'Kulambu'],
  },
  {
    id: '9',
    name_english: 'Red Snapper',
    name_tamil: 'சங்கரா',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Premium red snapper, excellent for special occasions. Mild and sweet flavor.',
    price_per_kg: 580,
    images: ['/images/fish/sea-fish/snapper-1.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
      { id: 'fillet', name: 'Fillet', name_tamil: 'ஃபில்லட்', price_modifier: 60 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 100, protein: 20, fat: 1.3, omega3: 0.3 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.7,
    reviews_count: 112,
    best_for: ['Grill', 'Bake', 'Curry'],
  },
  {
    id: '10',
    name_english: 'Anchovy (Nethili)',
    name_tamil: 'நெத்திலி',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Small, flavorful anchovies. Perfect for crispy fry or nethili kulambu.',
    price_per_kg: 180,
    images: ['/images/fish/sea-fish/anchovy-1.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 20 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 131, protein: 20, fat: 4.8, omega3: 1.5 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.6,
    reviews_count: 198,
    best_for: ['Fry', 'Kulambu'],
  },
  {
    id: '11',
    name_english: 'Lobster',
    name_tamil: 'சிங்கி இறால்',
    category_id: 'special',
    category: { id: 'special', name_english: 'Special/Seasonal', name_tamil: 'சிறப்பு' },
    description: 'Premium fresh lobster for special occasions. Rich, buttery flavor.',
    price_per_kg: 1800,
    images: ['/images/fish/sea-fish/lobster-1.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole Live', name_tamil: 'உயிருடன்', price_modifier: 0 },
    ],
    availability_status: 'limited' as const,
    nutritional_info: { calories: 89, protein: 19, fat: 0.9, omega3: 0.4 },
    freshness_date: new Date(),
    fish_type: 'special' as const,
    is_active: true,
    rating: 4.9,
    reviews_count: 45,
    best_for: ['Grill', 'Butter Garlic', 'Thermidor'],
  },
  {
    id: '12',
    name_english: 'Sardine (Mathi)',
    name_tamil: 'மத்தி',
    category_id: 'sea',
    category: { id: 'sea', name_english: 'Sea Fish', name_tamil: 'கடல் மீன்' },
    description: 'Fresh sardines, highly nutritious and affordable. Great for everyday meals.',
    price_per_kg: 150,
    images: ['/images/fish/sea-fish/sardine-1.jpg'],
    cleaning_options: [
      { id: 'whole', name: 'Whole', name_tamil: 'முழுமையாக', price_modifier: 0 },
      { id: 'cleaned', name: 'Cleaned', name_tamil: 'சுத்தம்', price_modifier: 0 },
    ],
    availability_status: 'in_stock' as const,
    nutritional_info: { calories: 208, protein: 25, fat: 11, omega3: 1.5 },
    freshness_date: new Date(),
    fish_type: 'sea' as const,
    is_active: true,
    rating: 4.4,
    reviews_count: 287,
    best_for: ['Fry', 'Curry', 'Kulambu'],
  },
];

export const MOCK_ORDERS = [
  {
    id: 'ORD001',
    user_id: 'user1',
    items: [
      { product: MOCK_PRODUCTS[0], quantity: 1, unit: 'kg', cleaning_type: 'steaks', total_price: 880 },
      { product: MOCK_PRODUCTS[2], quantity: 0.5, unit: 'kg', cleaning_type: 'cleaned', total_price: 375 },
    ],
    subtotal: 1255,
    delivery_charge: 0,
    discount_amount: 50,
    total_amount: 1205,
    order_status: 'delivered' as const,
    payment_method: 'upi' as const,
    payment_status: 'paid' as const,
    delivery_slot: { name: 'Morning Delivery', time: '8:00 AM - 12:00 PM' },
    delivery_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    address: {
      full_address: '42, Gandhi Street, T. Nagar',
      landmark: 'Near Pondy Bazaar',
      city: 'Chennai',
      pincode: '600017',
    },
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'ORD002',
    user_id: 'user1',
    items: [
      { product: MOCK_PRODUCTS[1], quantity: 2, unit: 'piece', cleaning_type: 'cleaned', total_price: 760 },
    ],
    subtotal: 760,
    delivery_charge: 30,
    discount_amount: 0,
    total_amount: 790,
    order_status: 'out_for_delivery' as const,
    payment_method: 'cod' as const,
    payment_status: 'pending' as const,
    delivery_slot: { name: 'Evening Delivery', time: '4:00 PM - 7:00 PM' },
    delivery_date: new Date(),
    address: {
      full_address: '42, Gandhi Street, T. Nagar',
      landmark: 'Near Pondy Bazaar',
      city: 'Chennai',
      pincode: '600017',
    },
    delivery_partner: {
      name: 'Rajan K',
      phone: '+91 98765 43210',
      photo: '/images/delivery/rajan.jpg',
    },
    tracking: {
      current_lat: 13.0418,
      current_lng: 80.2341,
      eta: '25 mins',
    },
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    id: 'ORD003',
    user_id: 'user1',
    items: [
      { product: MOCK_PRODUCTS[4], quantity: 1, unit: 'kg', cleaning_type: 'cleaned', total_price: 510 },
      { product: MOCK_PRODUCTS[7], quantity: 0.5, unit: 'kg', cleaning_type: 'cleaned', total_price: 110 },
    ],
    subtotal: 620,
    delivery_charge: 0,
    discount_amount: 0,
    total_amount: 620,
    order_status: 'processing' as const,
    payment_method: 'upi' as const,
    payment_status: 'paid' as const,
    delivery_slot: { name: 'Sunrise Delivery', time: '6:00 AM - 8:00 AM' },
    delivery_date: new Date(Date.now() + 24 * 60 * 60 * 1000),
    address: {
      full_address: '15, Lake View Road, Nungambakkam',
      landmark: 'Opposite to Park',
      city: 'Chennai',
      pincode: '600034',
    },
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
];

export const MOCK_RECIPES = [
  {
    id: '1',
    title_english: 'Meen Kulambu (Fish Curry)',
    title_tamil: 'மீன் குழம்பு',
    fish_product: MOCK_PRODUCTS[0],
    video_url: 'https://youtube.com/watch?v=example1',
    thumbnail: '/images/recipes/meen-kulambu.jpg',
    description: 'Traditional Tamil Nadu style fish curry with tamarind and spices.',
    difficulty_level: 'medium' as const,
    cooking_time: 45,
    servings: 4,
    cuisine_type: 'Tamil',
    ingredients: [
      { name: 'Seer Fish', quantity: '500g', is_fish: true },
      { name: 'Tamarind', quantity: '1 lemon size', is_fish: false },
      { name: 'Onion', quantity: '2 medium', is_fish: false },
      { name: 'Tomato', quantity: '2 medium', is_fish: false },
      { name: 'Sambar powder', quantity: '2 tbsp', is_fish: false },
      { name: 'Turmeric', quantity: '1/2 tsp', is_fish: false },
    ],
    steps: [
      { step_number: 1, instruction: 'Clean and marinate fish with turmeric and salt' },
      { step_number: 2, instruction: 'Soak tamarind in warm water and extract juice' },
      { step_number: 3, instruction: 'Heat oil and splutter mustard seeds, fenugreek' },
      { step_number: 4, instruction: 'Add onions and sauté until golden' },
      { step_number: 5, instruction: 'Add tomatoes and cook until soft' },
      { step_number: 6, instruction: 'Add sambar powder, tamarind juice and simmer' },
      { step_number: 7, instruction: 'Gently add fish pieces and cook for 10-12 mins' },
    ],
    rating: 4.8,
    reviews_count: 156,
    is_active: true,
  },
  {
    id: '2',
    title_english: 'Prawn Biriyani',
    title_tamil: 'இறால் பிரியாணி',
    fish_product: MOCK_PRODUCTS[2],
    video_url: 'https://youtube.com/watch?v=example2',
    thumbnail: '/images/recipes/prawn-biriyani.jpg',
    description: 'Aromatic prawn biriyani with basmati rice and special spices.',
    difficulty_level: 'hard' as const,
    cooking_time: 60,
    servings: 6,
    cuisine_type: 'Tamil',
    ingredients: [
      { name: 'Tiger Prawns', quantity: '500g', is_fish: true },
      { name: 'Basmati Rice', quantity: '2 cups', is_fish: false },
      { name: 'Onion', quantity: '3 large', is_fish: false },
      { name: 'Yogurt', quantity: '1/2 cup', is_fish: false },
      { name: 'Biriyani masala', quantity: '2 tbsp', is_fish: false },
    ],
    steps: [
      { step_number: 1, instruction: 'Clean prawns and marinate with yogurt and spices' },
      { step_number: 2, instruction: 'Soak basmati rice for 30 minutes' },
      { step_number: 3, instruction: 'Fry onions until golden brown for garnish' },
      { step_number: 4, instruction: 'Cook prawns with spices until done' },
      { step_number: 5, instruction: 'Layer rice and prawn masala, dum cook for 20 mins' },
    ],
    rating: 4.9,
    reviews_count: 203,
    is_active: true,
  },
  {
    id: '3',
    title_english: 'Fish Fry (Meen Varuval)',
    title_tamil: 'மீன் வறுவல்',
    fish_product: MOCK_PRODUCTS[1],
    video_url: 'https://youtube.com/watch?v=example3',
    thumbnail: '/images/recipes/fish-fry.jpg',
    description: 'Crispy South Indian style fish fry with aromatic spices.',
    difficulty_level: 'easy' as const,
    cooking_time: 25,
    servings: 4,
    cuisine_type: 'Tamil',
    ingredients: [
      { name: 'Pomfret', quantity: '4 pieces', is_fish: true },
      { name: 'Red chilli powder', quantity: '2 tbsp', is_fish: false },
      { name: 'Turmeric', quantity: '1/2 tsp', is_fish: false },
      { name: 'Ginger garlic paste', quantity: '1 tbsp', is_fish: false },
      { name: 'Lemon juice', quantity: '2 tbsp', is_fish: false },
    ],
    steps: [
      { step_number: 1, instruction: 'Make slits on both sides of the fish' },
      { step_number: 2, instruction: 'Mix all spices with lemon juice to make paste' },
      { step_number: 3, instruction: 'Apply paste on fish and marinate for 30 mins' },
      { step_number: 4, instruction: 'Heat oil in a pan and shallow fry until crispy' },
    ],
    rating: 4.7,
    reviews_count: 312,
    is_active: true,
  },
  {
    id: '4',
    title_english: 'Crab Masala',
    title_tamil: 'நண்டு மசாலா',
    fish_product: MOCK_PRODUCTS[4],
    video_url: 'https://youtube.com/watch?v=example4',
    thumbnail: '/images/recipes/crab-masala.jpg',
    description: 'Spicy Chettinad style crab masala with coconut.',
    difficulty_level: 'medium' as const,
    cooking_time: 50,
    servings: 4,
    cuisine_type: 'Chettinad',
    ingredients: [
      { name: 'Crab', quantity: '1 kg', is_fish: true },
      { name: 'Coconut', quantity: '1/2 cup grated', is_fish: false },
      { name: 'Onion', quantity: '2 medium', is_fish: false },
      { name: 'Curry leaves', quantity: '2 sprigs', is_fish: false },
    ],
    steps: [
      { step_number: 1, instruction: 'Clean crabs and separate claws' },
      { step_number: 2, instruction: 'Grind coconut with spices for masala' },
      { step_number: 3, instruction: 'Cook crabs with masala until done' },
    ],
    rating: 4.6,
    reviews_count: 89,
    is_active: true,
  },
  {
    id: '5',
    title_english: 'Kerala Fish Molee',
    title_tamil: 'கேரளா மீன் மொய்லி',
    fish_product: MOCK_PRODUCTS[8],
    video_url: 'https://youtube.com/watch?v=example5',
    thumbnail: '/images/recipes/fish-molee.jpg',
    description: 'Creamy Kerala style fish curry with coconut milk.',
    difficulty_level: 'easy' as const,
    cooking_time: 35,
    servings: 4,
    cuisine_type: 'Kerala',
    ingredients: [
      { name: 'Red Snapper', quantity: '500g', is_fish: true },
      { name: 'Coconut milk', quantity: '2 cups', is_fish: false },
      { name: 'Green chillies', quantity: '3-4', is_fish: false },
      { name: 'Ginger', quantity: '1 inch', is_fish: false },
    ],
    steps: [
      { step_number: 1, instruction: 'Marinate fish with turmeric and salt' },
      { step_number: 2, instruction: 'Sauté onions, ginger, green chillies' },
      { step_number: 3, instruction: 'Add coconut milk and bring to simmer' },
      { step_number: 4, instruction: 'Add fish and cook gently for 10 mins' },
    ],
    rating: 4.8,
    reviews_count: 134,
    is_active: true,
  },
  {
    id: '6',
    title_english: 'Squid Roast',
    title_tamil: 'கணவாய் வறுவல்',
    fish_product: MOCK_PRODUCTS[6],
    video_url: 'https://youtube.com/watch?v=example6',
    thumbnail: '/images/recipes/squid-roast.jpg',
    description: 'Spicy dry squid roast with pepper and curry leaves.',
    difficulty_level: 'easy' as const,
    cooking_time: 20,
    servings: 3,
    cuisine_type: 'Tamil',
    ingredients: [
      { name: 'Squid rings', quantity: '400g', is_fish: true },
      { name: 'Black pepper', quantity: '1 tbsp', is_fish: false },
      { name: 'Curry leaves', quantity: '2 sprigs', is_fish: false },
    ],
    steps: [
      { step_number: 1, instruction: 'Clean squid and cut into rings' },
      { step_number: 2, instruction: 'Marinate with spices' },
      { step_number: 3, instruction: 'Stir fry on high heat until done' },
    ],
    rating: 4.5,
    reviews_count: 78,
    is_active: true,
  },
];

export const MOCK_USER = {
  id: 'user1',
  name: 'Priya Sharma',
  mobile_primary: '+91 98765 43210',
  mobile_alternative: '+91 98765 43211',
  email: 'priya.sharma@email.com',
  referral_code: 'PRIYA50',
  referred_by: null,
  preferred_language: 'en' as const,
  profile_picture: '/images/users/priya.jpg',
  wallet_balance: 150,
  total_orders: 23,
  addresses: [
    {
      id: 'addr1',
      full_address: '42, Gandhi Street, T. Nagar',
      landmark: 'Near Pondy Bazaar',
      city: 'Chennai',
      pincode: '600017',
      latitude: 13.0418,
      longitude: 80.2341,
      is_default: true,
      address_type: 'home' as const,
    },
    {
      id: 'addr2',
      full_address: '15, Lake View Road, Nungambakkam',
      landmark: 'Opposite to Park',
      city: 'Chennai',
      pincode: '600034',
      latitude: 13.0569,
      longitude: 80.2425,
      is_default: false,
      address_type: 'work' as const,
    },
  ],
  referrals: [
    { name: 'Anitha R', date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000), earned: 50, status: 'credited' },
    { name: 'Kumar S', date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), earned: 50, status: 'credited' },
    { name: 'Lakshmi M', date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), earned: 50, status: 'pending' },
  ],
};

export const MOCK_CART = {
  items: [
    {
      id: 'cart1',
      product: MOCK_PRODUCTS[0],
      quantity: 1,
      unit: 'kg' as const,
      cleaning_type: 'steaks',
      unit_price: 880,
      total_price: 880,
    },
    {
      id: 'cart2',
      product: MOCK_PRODUCTS[2],
      quantity: 0.5,
      unit: 'kg' as const,
      cleaning_type: 'cleaned',
      unit_price: 700,
      total_price: 350,
    },
  ],
  subtotal: 1230,
  delivery_charge: 0,
  discount_amount: 50,
  coupon_code: 'FIRST50',
  total: 1180,
};

// Admin Dashboard Stats
export const ADMIN_STATS = {
  today: {
    orders: 47,
    revenue: 42350,
    new_customers: 12,
    avg_order_value: 901,
  },
  week: {
    orders: 312,
    revenue: 287650,
    new_customers: 67,
    avg_order_value: 922,
  },
  month: {
    orders: 1247,
    revenue: 1156780,
    new_customers: 234,
    avg_order_value: 928,
  },
  recent_orders: MOCK_ORDERS,
  low_stock: [
    { product: MOCK_PRODUCTS[3], stock: 5 },
    { product: MOCK_PRODUCTS[10], stock: 3 },
  ],
  top_products: [
    { product: MOCK_PRODUCTS[0], sold: 156 },
    { product: MOCK_PRODUCTS[2], sold: 134 },
    { product: MOCK_PRODUCTS[1], sold: 98 },
  ],
};
